import { motion } from "framer-motion";
import {
  TrendingUp,
  TrendingDown,
  Minus,
  BrainCircuit,
  ShieldAlert,
  Sparkles,
  ArrowUpRight,
} from "lucide-react";

import { SectionCard, StatusBadge } from "../../ui";

type Recommendation = "BUY" | "HOLD" | "REDUCE";

interface InsightCardProps {
  recommendation?: Recommendation;
  stock?: string;
  confidence?: number;
  summary?: string;
  risk?: "Low" | "Moderate" | "High";
}

const recommendationConfig = {
  BUY: {
    icon: TrendingUp,
    positive: true,
  },
  HOLD: {
    icon: Minus,
    positive: true,
  },
  REDUCE: {
    icon: TrendingDown,
    positive: false,
  },
};

export default function InsightCard({
  recommendation = "BUY",
  stock = "Infosys",
  confidence = 94,
  summary = "Strong earnings momentum supported by improving AI demand, stable cash flow and attractive valuation versus peers.",
  risk = "Moderate",
}: InsightCardProps) {
  const config = recommendationConfig[recommendation];
  const Icon = config.icon;

  return (
    <SectionCard
      title="AI Investment Insight"
      subtitle="Generated by FinSight AI"
      icon={<BrainCircuit size={24} />}
      action={<Sparkles className="text-emerald-400" size={22} />}
    >
      <div className="space-y-6">

        <motion.div
          whileHover={{ scale: 1.01 }}
          className="flex items-center justify-between rounded-2xl border border-zinc-800 bg-zinc-800/40 p-5 transition-all"
        >
          <div>
            <p className="text-sm text-zinc-500">
              Recommendation
            </p>

            <h3 className="mt-2 text-3xl font-bold text-zinc-100">
              {stock}
            </h3>
          </div>

          <StatusBadge positive={config.positive}>
            <div className="flex items-center gap-2">
              <Icon size={16} />
              {recommendation}
            </div>
          </StatusBadge>
        </motion.div>

        <div>
          <div className="mb-3 flex items-center justify-between">
            <span className="text-sm text-zinc-500">
              AI Confidence
            </span>

            <span className="font-mono text-xl font-semibold text-zinc-100">
              {confidence}%
            </span>
          </div>

          <div className="h-3 overflow-hidden rounded-full bg-zinc-800">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${confidence}%` }}
              transition={{
                duration: 1,
              }}
              className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-emerald-300"
            />
          </div>
        </div>

        <div className="rounded-2xl border border-zinc-800 bg-zinc-800/40 p-5">
          <div className="mb-3 flex items-center gap-2">
            <ArrowUpRight
              size={18}
              className="text-emerald-400"
            />

            <h4 className="font-semibold text-zinc-100">
              AI Summary
            </h4>
          </div>

          <p className="leading-7 text-zinc-400">
            {summary}
          </p>
        </div>

        <div className="flex items-center justify-between rounded-2xl border border-zinc-800 bg-zinc-800/40 p-5">
          <div className="flex items-center gap-3">
            <ShieldAlert
              size={18}
              className="text-amber-400"
            />

            <span className="font-medium text-zinc-200">
              Risk Level
            </span>
          </div>

          <StatusBadge positive={risk !== "High"}>
            {risk}
          </StatusBadge>
        </div>

      </div>
    </SectionCard>
  );
}